
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
# this experiment name is only used for the jobs started by CI/CD, not for the jobs started by schedule
experiment_name: rdam_green_space_monitoring_experiment

settings:
  default_compute: azureml:cpu001-compute
  # write to workspaceblobstore by default, used for transfering data between components. use datascience for actual input/output.
  default_datastore: azureml:workspaceblobstore
  # enable force rerun to disable caching. caching can be useful, but may have unintended consequences when not set up
  # correctly.
  force_rerun: true

# <inputs_and_outputs>
inputs:
  operator: "multiply"
  a: 2
  b: 3
# </inputs_and_outputs>

# <jobs>
jobs:
  component_a:
    type: command
    compute: azureml:cpu001-compute
    # this component is created in the ci/cd pipeline before creating the pipelinejob
    component: azureml:rdam_green_space_monitoring_component_a@latest
    limits:
      timeout: 21600  # timeout in seconds (now set to 6 hours), adjust if needed
    inputs:
      operator: ${{parent.inputs.operator}}
      a: ${{parent.inputs.a}}
      b: ${{parent.inputs.b}}
    environment_variables:
      # example setting an environment variable. use only for setting non-secret variables.
      # set secret variables in keyvault (https://wiki.rotterdam.nl/x/DD1cDg) or pass from devops library.
      KEYVAULT_NAME: PASSED_BY_DEPLOYMENT_YML
  component_b:
    type: command
    compute: azureml:cpu001-compute
    # this component is created in the ci/cd pipeline before creating the pipelinejob
    component: azureml:rdam_green_space_monitoring_component_b@latest
    limits:
      timeout: 21600  # timeout in seconds (now set to 6 hours), adjust if needed
    inputs:
      operator: ${{parent.inputs.operator}}
      a: ${{parent.inputs.a}}
      b: ${{parent.inputs.b}}
# </jobs>
