name: example_package
channels:
  - defaults
dependencies:
  - python=3.11
  - pip:
    # this is a package registered in the artifacts feed specified below (from a package repo)
    - example_package==0.0.1
    - >-
      --extra-index-url
      https://pkgs.dev.azure.com/organisation_name/rdam/_packaging/package_feed@#{feed_view}#/pypi/simple/
